---
Name: salepriceconfig
---
SilverCommerce\CatalogueAdmin\Model\CatalogueProduct:
  extensions:
    - SilverCommerce\SalePrices\CatalogueProductExtension

SilverCommerce\OrdersAdmin\Model\LineItem:
  extensions:
    - SilverCommerce\SalePrices\LineItemExtension